create table if not exists public.client_presence (
    install_id text primary key,
    session_name text not null,
    client_type text not null default 'unknown',
    app_version text not null default '',
    username text,
    user_id bigint references public.users(id) on delete set null,
    ip_address text,
    ip_country text,
    user_agent text,
    last_path text not null default '',
    last_event text not null default '',
    first_seen_at timestamptz not null default timezone('utc', now()),
    last_seen_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.activity_logs (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default timezone('utc', now()),
    event_type text not null,
    request_path text not null,
    install_id text,
    session_name text,
    client_type text,
    app_version text,
    username text,
    user_id bigint references public.users(id) on delete set null,
    ip_address text,
    ip_country text,
    user_agent text
);

create index if not exists activity_logs_created_at_idx on public.activity_logs (created_at desc);
create index if not exists activity_logs_username_idx on public.activity_logs (username);
create index if not exists activity_logs_install_id_idx on public.activity_logs (install_id);
create index if not exists client_presence_last_seen_idx on public.client_presence (last_seen_at desc);

alter table public.client_presence enable row level security;
alter table public.activity_logs enable row level security;

revoke all on table public.client_presence from anon, authenticated;
revoke all on table public.activity_logs from anon, authenticated;

grant all on table public.client_presence to service_role;
grant all on table public.activity_logs to service_role;
