create table if not exists public.users (
    id bigint generated by default as identity primary key,
    username text not null unique,
    password_hash text not null,
    xp integer not null default 0 check (xp >= 0),
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.sessions (
    token text primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.lesson_progress (
    user_id bigint not null references public.users(id) on delete cascade,
    lesson_id text not null,
    score smallint not null check (score in (0, 1)),
    completed_at timestamptz not null default timezone('utc', now()),
    primary key (user_id, lesson_id)
);

create index if not exists sessions_user_id_idx on public.sessions (user_id);
create index if not exists lesson_progress_user_id_idx on public.lesson_progress (user_id);
create index if not exists lesson_progress_completed_at_idx on public.lesson_progress (completed_at desc);

alter table public.users enable row level security;
alter table public.sessions enable row level security;
alter table public.lesson_progress enable row level security;

create or replace function public.pyquest_record_lesson_result(
    target_user_id bigint,
    target_lesson_id text,
    selected_score smallint,
    full_xp integer,
    partial_xp integer
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    existing_score smallint;
    xp_delta integer := 0;
begin
    select score
    into existing_score
    from public.lesson_progress
    where user_id = target_user_id and lesson_id = target_lesson_id;

    if existing_score is null then
        insert into public.lesson_progress (user_id, lesson_id, score)
        values (target_user_id, target_lesson_id, selected_score);

        xp_delta := case
            when selected_score = 1 then full_xp
            else partial_xp
        end;
    elsif existing_score = 0 and selected_score = 1 then
        update public.lesson_progress
        set score = 1,
            completed_at = timezone('utc', now())
        where user_id = target_user_id and lesson_id = target_lesson_id;

        xp_delta := greatest(full_xp - partial_xp, 0);
    end if;

    if xp_delta > 0 then
        update public.users
        set xp = xp + xp_delta
        where id = target_user_id;
    end if;

    return xp_delta;
end;
$$;

create or replace function public.pyquest_leaderboard()
returns table (
    username text,
    xp integer,
    completed_lessons bigint
)
language sql
security definer
set search_path = public
as $$
    select
        users.username,
        users.xp,
        count(lesson_progress.lesson_id) as completed_lessons
    from public.users
    left join public.lesson_progress on lesson_progress.user_id = users.id
    group by users.id, users.username, users.xp
    order by users.xp desc, completed_lessons desc, users.username asc
    limit 25;
$$;

revoke all on table public.users from anon, authenticated;
revoke all on table public.sessions from anon, authenticated;
revoke all on table public.lesson_progress from anon, authenticated;

revoke all on function public.pyquest_record_lesson_result(bigint, text, smallint, integer, integer) from public, anon, authenticated;
revoke all on function public.pyquest_leaderboard() from public, anon, authenticated;

grant usage on schema public to service_role;
grant all on table public.users to service_role;
grant all on table public.sessions to service_role;
grant all on table public.lesson_progress to service_role;
grant execute on function public.pyquest_record_lesson_result(bigint, text, smallint, integer, integer) to service_role;
grant execute on function public.pyquest_leaderboard() to service_role;
